# -*- coding: utf-8 -*-
"""Transformation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nx1XZ3CzGw4yPHww2gnTjEN6uKF9UgVZ
"""

import pandas as pd
df=pd.read_csv('/content/Titanic-Dataset.csv', usecols=['Pclass', 'Age', 'Fare', 'Survived'])
df.head()

df['Age'].fillna(df.Age.median(),inplace=True)

df.isnull().sum()

X=df.iloc[:, 1:]
y=df.iloc[:, 0]
X

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
X_train

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_train_scaled

X_test_scaled=scaler.transform(X_test)
X_test_scaled

